# test purposes only

sudo docker run \
  -e AAD_CLIENT_ID=$AAD_CLIENT_ID \
  -e AAD_SECRET=$AAD_SECRET \
  -e AAD_TENANT=$AAD_TENANT \
  -e STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME \
  -e STORAGE_ACCOUNT_KEY=$STORAGE_ACCOUNT_KEY \
  -e ADMIN_USER_NAME=$ADMIN_USER_NAME\
  -e ADMIN_USER_PASSWORD=$ADMIN_USER_PASSWORD \
  -e SUBSCRIPTION_ID=$SUBSCRIPTION_ID \
  -e RESOURCE_GROUP_NAME=$RESOURCE_GROUP_NAME \
  -e REGION=$REGION \
  -e AZURE_CONTAINER_NAME=$AZURE_CONTAINER_NAME \
  -e FS_SCRIPT_DIRECTORY=$FS_SCRIPT_DIRECTORY \
  -e FS_RESULT_DIRECTORY=$FS_RESULT_DIRECTORY \
  -e FS_MODEL_DIRECTORY=$FS_MODEL_DIRECTORY \
  -e FS_DATA_DIRECTORY=$FS_DATA_DIRECTORY \
  -e LOCAL_SCRIPT_FILE=$LOCAL_SCRIPT_FILE \
  -e LOCAL_SCRIPT_PATH=$LOCAL_SCRIPT_PATH \
  -e LOCAL_MODEL_FILE=$LOCAL_MODEL_FILE \
  -e LOCAL_MODEL_PATH=$LOCAL_MODEL_PATH \
  -e WORKSPACE=$WORKSPACE \
  -e JOB_EXPERIMENT_NAME=$JOB_EXPERIMENT_NAME \
  -e JOB_NAME_PREFIX=$JOB_NAME_PREFIX \
  -e JOB_NODE_COUNT=$JOB_NODE_COUNT \
  -e CLUSTER_NAME=$CLUSTER_NAME \
  -e CLUSTER_CONTAINER_MNT_PATH=$CLUSTER_CONTAINER_MNT_PATH \
  -e CLUSTER_VM_SIZE=$CLUSTER_VM_SIZE \
  -e CLUSTER_VM_PRIORITY=$CLUSTER_VM_PRIORITY \
  -e CLUSTER_AUTO_SCALE=$CLUSTER_AUTO_SCALE \
  -e CLUSTER_STATIC_NODE_COUNT=$CLUSTER_STATIC_NODE_COUNT \
  -e CLUSTER_MINIMUM_NODE_COUNT=$CLUSTER_MINIMUM_NODE_COUNT \
  -e CLUSTER_MAXIMUM_NODE_COUNT=$CLUSTER_MAXIMUM_NODE_COUNT \
  -e CLUSTER_INITIAL_NODE_COUNT=$CLUSTER_INITIAL_NODE_COUNT \
  bait_job
